name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Ou a branch principal do seu projeto
    paths:
      - 'lib/**'
      - 'web/**'
      - 'pubspec.yaml'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5' # Mude se necessário

      - name: Rodar build do Flutter Web
        run: flutter build web --base-href /revista_feedback/

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages # A branch onde o site será publicado